### ISSUE TITLE
SyntaxError: Unexpected token '{'

### ISSUE THREAD

**Issue by Hilmaar** [waveplate/discord-irc-relay#1]
Hi! Looks like an awesome project and I really want to use it!

However when I try to run it I get the following error:

```
hilmar@spicy:~/discord-irc-relay/discord-irc-relay$ node .
/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/@discordjs/rest/dist/index.js:175
  static {
         ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/discord.js/src/client/BaseClient.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
```

![image](https://github.com/waveplate/discord-irc-relay/assets/58349731/92702da1-b5d8-49ab-9ab9-a29c071544ac)

I may have just done something wrong or skipped a step, I'm not very familiar with with nodejs or npm. 

Thanks!

**Comment by waveplate** [comment]
which version of node are you using? you can find out by running `node --version`

and the version of the discord.js package as well by running `npm view discord.js version`

**Comment by Hilmaar** [comment]
> which version of node are you using? you can find out by running `node --version`
> 
> and the version of the discord.js package as well by running `npm view discord.js version`

I'm sorry for the late reply
 ```
npm view discord.js version
14.13.0
``` 
```
node --version
v18.17.1
```

I just tried running `node .` again, but now I'm getting a different result for some reason;

```
/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/@discordjs/ws/dist/index.js:1132
          error: new Error("Used disallowed intents")
                 ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/@discordjs/ws/dist/index.js:1132:18)
    at connection.onclose (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/@discordjs/ws/dist/index.js:676:17)
    at callListener (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emitClose (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/ws/lib/websocket.js:258:10)
    at TLSSocket.socketOnClose (/home/hilmar/discord-irc-relay/discord-irc-relay/node_modules/ws/lib/websocket.js:1264:15)
    at TLSSocket.emit (node:events:526:35)
    at node:net:323:12
    at TCP.done (node:_tls_wrap:588:7)

Node.js v18.17.1
```

**Comment by waveplate** [comment]
`discord-irc-relay` is trying to use some intents which you've not enabled in the discord bot developer portal.

        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.MessageContent,
        GatewayIntentBits.GuildMembers

you need to check all the boxes under "Privileged Gateway Intents" in the discord bot portal, as well as the "Read Messages/View Channels", "Send Messages" and "Read Message History" boxes under bot permissions

then generate your bot token again. that should fix these errors

**Comment by Hilmaar** [comment]
I did as you said, and it's working now. Thank you! :)

**Comment by waveplate** [comment]
no worries! issue closed.
